apiVersion: batch/v1
kind: CronJob
metadata:
  name: gke-vpa-recommender
  namespace: default
spec:
  schedule: "0 0 * * *"  # Schedule to run daily at midnight
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: workload-recommender
          containers:
          - name: vpa-recommender-container
            image: us-central1-docker.pkg.dev/gke-rightsize/main/workload-vpa-recs-image:latest
            imagePullPolicy: Always
            command: ["python"]
            args: ["/app/main.py"]  # Path to your Python script
            env:
            - name: CONFIG_PATH  # Path to the namespace file
              value: "/app/config/namespace.txt"
            - name: PROJECT_ID  # Read from ConfigMap
              valueFrom:
                configMapKeyRef:
                  name: namespace-config
                  key: PROJECT_ID
            - name: BIGQUERY_DATASET
              valueFrom:
                configMapKeyRef:
                  name: namespace-config
                  key: BIGQUERY_DATASET
            - name: BIGQUERY_TABLE
              valueFrom:
                configMapKeyRef:
                  name: namespace-config
                  key: BIGQUERY_TABLE
            - name: DEFAULT_WINDOW_DAYS
              valueFrom:
                configMapKeyRef:
                  name: namespace-config
                  key: DEFAULT_WINDOW_DAYS
            - name: MEMORY_RECOMMENDATION_BUFFER
              valueFrom:
                configMapKeyRef:
                  name: namespace-config
                  key: MEMORY_RECOMMENDATION_BUFFER
            volumeMounts:
            - name: namespace-config-volume
              mountPath: /app/config/namespace.txt
              subPath: namespace.txt
              readOnly: true
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 250m
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 1000
          restartPolicy: Never
          volumes:
          - name: namespace-config-volume
            configMap:
              name: namespace-config
