# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bigquery_record.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'bigquery_record.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62igquery_record.proto\x12\x0f\x62igquery_schema\"\x82\x05\n\x0e\x42igQueryRecord\x12\x10\n\x08run_date\x18\x01 \x01(\t\x12\x16\n\x0estart_datetime\x18\x02 \x01(\t\x12\x14\n\x0c\x65nd_datetime\x18\x03 \x01(\t\x12\x12\n\nproject_id\x18\x04 \x01(\t\x12\x10\n\x08location\x18\x05 \x01(\t\x12\x14\n\x0c\x63luster_name\x18\x06 \x01(\t\x12\x16\n\x0enamespace_name\x18\x07 \x01(\t\x12\x17\n\x0f\x63ontroller_name\x18\x08 \x01(\t\x12\x17\n\x0f\x63ontroller_type\x18\t \x01(\t\x12\x16\n\x0e\x63ontainer_name\x18\n \x01(\t\x12\x17\n\x0f\x63pu_mcore_usage\x18\x0b \x01(\x02\x12\x1c\n\x14\x63pu_requested_mcores\x18\x0c \x01(\x02\x12\x18\n\x10\x63pu_limit_mcores\x18\r \x01(\x02\x12\x1c\n\x14memory_mib_usage_max\x18\x0e \x01(\x02\x12\x1c\n\x14memory_requested_mib\x18\x0f \x01(\x02\x12\x18\n\x10memory_limit_mib\x18\x10 \x01(\x02\x12\x1f\n\x17\x63pu_request_utilization\x18\x11 \x01(\x02\x12\"\n\x1amemory_request_utilization\x18\x12 \x01(\x02\x12$\n\x1c\x63pu_requested_recommendation\x18\x13 \x01(\x02\x12 \n\x18\x63pu_limit_recommendation\x18\x14 \x01(\x02\x12\'\n\x1fmemory_requested_recommendation\x18\x15 \x01(\x02\x12#\n\x1bmemory_limit_recommendation\x18\x16 \x01(\x02\x12\x10\n\x08priority\x18\x17 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bigquery_record_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BIGQUERYRECORD']._serialized_start=43
  _globals['_BIGQUERYRECORD']._serialized_end=685
# @@protoc_insertion_point(module_scope)
